Updated quick start docs
opencadc/canfar-portal pull request #63
Opened 2021-06-28 21:21 UTC by sfabbro

Updating documentation with:
- feedback from various users (thanks Dustin Lang and others)
- update from Compute Canada
- updates on the default supported images.

2021-06-29 23:09 UTC, at88mph requested changes

2021-06-29 23:09 UTC, at88mph commented on docs/quick_start_en.md
> +This quick start guide will demonstrate how to create a basic source detection pipeline operating on CFHT Megacam images within the CANFAR Virtual Machine (VM), fast access to the CADC archive and st
` ... with fast access `?

2021-06-29 23:09 UTC, at88mph commented on docs/quick_start_en.md
> +```IMPORTANT``` : if you do not create a snapshot of the VM, your work of this VM will be lost if the VM is deleted. Volume-based VMs do not need snapshots and will persist the files directly on a pe
" ... if you do not create a snapshot of the VM, you will lose all of your work when the VM is deleted. ... "

2021-06-29 23:25 UTC, at88mph approved these changes

2021-06-29 23:25 UTC, merged

2021-06-30 00:23 UTC, sfabbro commented
More updates!